---

- name: playbook testing
  connection: local
  gather_facts: false
  hosts: candid


  tasks:
     - name: create a fabric
       candid_user_management:
           host: "{{ host }}"
           username: "{{ user }}"
           password: "{{ pass }}"
           user: test
           method: delete_user
           use_ssl: false
           validate_certs: false
